export const FAVORITES_TYPES = {
  FETCH_FAVORITES_REQUEST: "favorites/FETCH_FAVORITES_REQUEST",
  FETCH_FAVORITES_SUCCESS: "favorites/FETCH_FAVORITES_SUCCESS",
  FETCH_FAVORITES_FAILURE: "favorites/FETCH_FAVORITES_FAILURE",

  ADD_FAVORITE_REQUEST: "favorites/ADD_FAVORITE_REQUEST",
  ADD_FAVORITE_SUCCESS: "favorites/ADD_FAVORITE_SUCCESS",
  ADD_FAVORITE_FAILURE: "favorites/ADD_FAVORITE_FAILURE",

  REMOVE_FAVORITE_REQUEST: "favorites/REMOVE_FAVORITE_REQUEST",
  REMOVE_FAVORITE_SUCCESS: "favorites/REMOVE_FAVORITE_SUCCESS",
  REMOVE_FAVORITE_FAILURE: "favorites/REMOVE_FAVORITE_FAILURE",
};
