export const CATALOG_TYPES = {
  FETCH_HOME_REQUEST: "catalog/FETCH_HOME_REQUEST",
  FETCH_HOME_SUCCESS: "catalog/FETCH_HOME_SUCCESS",
  FETCH_HOME_FAILURE: "catalog/FETCH_HOME_FAILURE",

  FETCH_MOVIES_REQUEST: "catalog/FETCH_MOVIES_REQUEST",
  FETCH_MOVIES_SUCCESS: "catalog/FETCH_MOVIES_SUCCESS",
  FETCH_MOVIES_FAILURE: "catalog/FETCH_MOVIES_FAILURE",

  FETCH_SERIES_REQUEST: "catalog/FETCH_SERIES_REQUEST",
  FETCH_SERIES_SUCCESS: "catalog/FETCH_SERIES_SUCCESS",
  FETCH_SERIES_FAILURE: "catalog/FETCH_SERIES_FAILURE",

  FETCH_MATCHES_REQUEST: "catalog/FETCH_MATCHES_REQUEST",
  FETCH_MATCHES_SUCCESS: "catalog/FETCH_MATCHES_SUCCESS",
  FETCH_MATCHES_FAILURE: "catalog/FETCH_MATCHES_FAILURE",

  FETCH_GENRES_REQUEST: "catalog/FETCH_GENRES_REQUEST",
  FETCH_GENRES_SUCCESS: "catalog/FETCH_GENRES_SUCCESS",
  FETCH_GENRES_FAILURE: "catalog/FETCH_GENRES_FAILURE",

  FETCH_MOVIE_DETAIL_REQUEST: "catalog/FETCH_MOVIE_DETAIL_REQUEST",
  FETCH_MOVIE_DETAIL_SUCCESS: "catalog/FETCH_MOVIE_DETAIL_SUCCESS",
  FETCH_MOVIE_DETAIL_FAILURE: "catalog/FETCH_MOVIE_DETAIL_FAILURE",

  FETCH_SERIES_DETAIL_REQUEST: "catalog/FETCH_SERIES_DETAIL_REQUEST",
  FETCH_SERIES_DETAIL_SUCCESS: "catalog/FETCH_SERIES_DETAIL_SUCCESS",
  FETCH_SERIES_DETAIL_FAILURE: "catalog/FETCH_SERIES_DETAIL_FAILURE",

  FETCH_MATCH_DETAIL_REQUEST: "catalog/FETCH_MATCH_DETAIL_REQUEST",
  FETCH_MATCH_DETAIL_SUCCESS: "catalog/FETCH_MATCH_DETAIL_SUCCESS",
  FETCH_MATCH_DETAIL_FAILURE: "catalog/FETCH_MATCH_DETAIL_FAILURE",

  SEARCH_REQUEST: "catalog/SEARCH_REQUEST",
  SEARCH_SUCCESS: "catalog/SEARCH_SUCCESS",
  SEARCH_FAILURE: "catalog/SEARCH_FAILURE",
  SEARCH_CLEAR: "catalog/SEARCH_CLEAR",
};
