export const AUTH_TYPES = {
  BOOTSTRAP_REQUEST: "auth/BOOTSTRAP_REQUEST",
  BOOTSTRAP_SUCCESS: "auth/BOOTSTRAP_SUCCESS",
  BOOTSTRAP_FAILURE: "auth/BOOTSTRAP_FAILURE",

  AUTH_INITIATE_REQUEST: "auth/AUTH_INITIATE_REQUEST",
  AUTH_INITIATE_SUCCESS: "auth/AUTH_INITIATE_SUCCESS",
  AUTH_PASSWORD_REQUIRED: "auth/AUTH_PASSWORD_REQUIRED",

  AUTH_CONTINUE_REQUEST: "auth/AUTH_CONTINUE_REQUEST",
  AUTH_OTP_REQUIRED: "auth/AUTH_OTP_REQUIRED",
  AUTH_SUCCESS: "auth/AUTH_SUCCESS",
  AUTH_NEEDS_PASSWORD_SETUP: "auth/AUTH_NEEDS_PASSWORD_SETUP",
  AUTH_FAILURE: "auth/AUTH_FAILURE",
  AUTH_CLEAR_ERROR: "auth/AUTH_CLEAR_ERROR",

  AUTH_VERIFY_OTP_REQUEST: "auth/AUTH_VERIFY_OTP_REQUEST",
  AUTH_RESEND_OTP_REQUEST: "auth/AUTH_RESEND_OTP_REQUEST",
  AUTH_RESEND_OTP_SUCCESS: "auth/AUTH_RESEND_OTP_SUCCESS",

  AUTH_SET_PASSWORD_REQUEST: "auth/AUTH_SET_PASSWORD_REQUEST",
  AUTH_SET_PASSWORD_SUCCESS: "auth/AUTH_SET_PASSWORD_SUCCESS",
  AUTH_PROFILE_PASSWORD_SUCCESS: "auth/AUTH_PROFILE_PASSWORD_SUCCESS",

  AUTH_FORGOT_PASSWORD_REQUEST: "auth/AUTH_FORGOT_PASSWORD_REQUEST",
  AUTH_FORGOT_PASSWORD_SUCCESS: "auth/AUTH_FORGOT_PASSWORD_SUCCESS",
  AUTH_RESET_PASSWORD_REQUEST: "auth/AUTH_RESET_PASSWORD_REQUEST",
  AUTH_RESET_PASSWORD_SUCCESS: "auth/AUTH_RESET_PASSWORD_SUCCESS",

  AUTH_LOGOUT_REQUEST: "auth/AUTH_LOGOUT_REQUEST",
  AUTH_LOGOUT_SUCCESS: "auth/AUTH_LOGOUT_SUCCESS",
};
